// ═══════════════════════════════════════════════════
// CODE GENERATORS
// ═══════════════════════════════════════════════════
function genConfigH() {
  const spiBus = document.getElementById('spiBus').value;
  const spiInstance = spiBus === 'SPI_DRIVER_1' ? 'SPID1' : 'SPID0';
  const sck  = document.getElementById('spiSck').value.trim();
  const mosi = document.getElementById('spiMosi').value.trim();
  const miso = document.getElementById('spiMiso').value.trim();
  const cs   = document.getElementById('spiCs').value.trim();
  const cpi  = parseInt(document.getElementById('tbCpi').value) || 1600;
  const rot  = document.getElementById('tbRotation').value;
  const invertX  = isTgl('tgl-invertx');
  const invertY  = isTgl('tgl-inverty');
  const swapXY   = isTgl('tgl-swapxy');
  const autoMouse = isTgl('tgl-automouse');
  const aml = document.getElementById('autoMouseLayer').value;
  const amt = document.getElementById('autoMouseTimeout').value;
  const amd = document.getElementById('autoMouseDebounce').value;
  const combined   = isTgl('tgl-combined');
  const dragscroll = isTgl('tgl-dragscroll');

  let out = `// config.h — generated by QMK Visual Editor
// RP2040 + PMW3360 Split Keyboard

#pragma once

/* ── Bootloader ── */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
`;

  // No info.json equivalent for these:
  const usbPoll = parseInt(document.getElementById('cfgUsbPolling').value);
  if (usbPoll > 0 && usbPoll !== 1) out += `\n#define USB_POLLING_INTERVAL_MS ${usbPoll}`;

  // Right-half matrix overrides (MATRIX_*_PINS_RIGHT)
  const rowPinsRight = document.getElementById('matrixRowPinsRight').value.trim().split(/\s+/).filter(Boolean);
  const colPinsRight = document.getElementById('matrixColPinsRight').value.trim().split(/\s+/).filter(Boolean);
  if (rowPinsRight.length) out += `\n#define MATRIX_ROW_PINS_RIGHT { ${rowPinsRight.join(', ')} }`;
  if (colPinsRight.length) out += `\n#define MATRIX_COL_PINS_RIGHT { ${colPinsRight.join(', ')} }`;
  // Reverse cols for right half toggle
  if (isTgl('tgl-right-col-reverse')) {
    const reversed = matrixState.colPins.filter(Boolean).slice().reverse();
    if (reversed.length) out += `\n#define MATRIX_COL_PINS_RIGHT { ${reversed.join(', ')} }`;
  }

  const qtt = parseInt(document.getElementById('cfgQuickTapTerm').value);
  if (qtt > 0) out += `\n#define QUICK_TAP_TERM ${qtt}`;

  if (isTgl('tgl-mouse-ext')) out += `\n#define MOUSE_EXTENDED_REPORT`;

  // Split — only things with no info.json equivalent
  const masterSide = document.getElementById('masterSide')?.value || 'none';
  if (masterSide === 'left')  out += `\n#define MASTER_LEFT`;
  if (masterSide === 'right') out += `\n#define MASTER_RIGHT`;
  const sideDetect = document.getElementById('sideDetect').value;
  if (sideDetect === 'eeprom') out += `\n#define EE_HANDS`;
  if (isTgl('tgl-mirror'))   out += `\n#define SPLIT_TRANSPORT_MIRROR`;
  const tbSide = document.getElementById('tbSide').value;
  if (combined || tbSide === 'left' || tbSide === 'right') out += `\n#define SPLIT_POINTING_ENABLE`;


  let csPinsLine;
  if (tbSide === 'right') {
    csPinsLine = `#define PMW33XX_CS_PIN ${cs}\n#define POINTING_DEVICE_RIGHT`;
  } else if (tbSide === 'left') {
    csPinsLine = `#define PMW33XX_CS_PIN ${cs}\n#define POINTING_DEVICE_LEFT`;
  } else {
    csPinsLine = `#define PMW33XX_CS_PIN ${cs}`;
  }

  out += `

/* ── PMW3360 SPI ── */
#define SPI_DRIVER   ${spiInstance}
#define SPI_SCK_PIN  ${sck}
#define SPI_MOSI_PIN ${mosi}
#define SPI_MISO_PIN ${miso}
${csPinsLine}
#define PMW33XX_CPI ${cpi}
`;

  // PMW33xx requires -127..+127; convert 0-359 dial value to signed range
  const rotVal = parseInt(rot) || 0;
  const rotSigned = rotVal > 127 ? rotVal - 360 : rotVal;
  const rotClamped = Math.max(-127, Math.min(127, rotSigned));
  if (rotClamped !== 0) out += `#define ROTATIONAL_TRANSFORM_ANGLE ${rotClamped}\n`;
  const emitInvertX = invertX || swapXY;
  const emitInvertY = invertY || swapXY;
  if (emitInvertX) out += `#define POINTING_DEVICE_INVERT_X\n`;
  if (emitInvertY) out += `#define POINTING_DEVICE_INVERT_Y\n`;
  if (dragscroll) out += `#define POINTING_DEVICE_AUTO_MOUSE_ENABLE\n#define CHARYBDIS_AUTO_SNIPING_ON_LAYER ${aml}\n`;

  if (autoMouse) {
    const amlVal = parseInt(aml) || 1;
    const amtVal = parseInt(amt) || 650;
    const amdVal = parseInt(amd) || 25;
    out += `
/* ── Auto Mouse Layer ── */
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER ${amlVal}
#define AUTO_MOUSE_TIME ${amtVal}
#define AUTO_MOUSE_DEBOUNCE ${amdVal}
`;
  }

  return out;
}

function genRulesMk() {
  const tglMap = [
    ['POINTING_DEVICE_ENABLE', 'tgl-pde'],
    ['POINTING_DEVICE_DRIVER', null, 'pmw3360'],
    ['SPI_DRIVER_REQUIRED', 'tgl-spi'],
    ['CONSOLE_ENABLE', 'tgl-console'],
    ['COMMAND_ENABLE', 'tgl-command'],
    ['ENCODER_ENABLE', 'tgl-encoder'],
    ['RGBLIGHT_ENABLE', 'tgl-rgblight'],
    ['RGB_MATRIX_ENABLE', 'tgl-rgbmatrix'],
  ];

  let out = `# rules.mk — generated by QMK Visual Editor\n\n`;

  for (const entry of tglMap) {
    const [key, tglId, forced] = entry;
    if (forced) {
      out += `${key} = ${forced}\n`;
    } else {
      out += `${key} = ${isTgl(tglId) ? 'yes' : 'no'}\n`;
    }
  }
  return out;
}

function genInfoJson() {
  // Build object strictly following the QMK info.json schema
  // https://docs.qmk.fm/reference_info_json

  const rowPins = matrixState.rowPins.filter(Boolean);
  const colPins = matrixState.colPins.filter(Boolean);

  const obj = {
    // ── General Metadata ──
    keyboard_name: document.getElementById('kbName').value || 'my_split_kb',
    manufacturer:  document.getElementById('kbMfr').value  || 'handwired',
    maintainer:    document.getElementById('kbMaintainer').value || 'qmk',
    url: '',

    // ── Hardware ──
    processor:  'RP2040',
    bootloader: document.getElementById('bootloader').value,
    board:      document.getElementById('board').value,

    // ── USB ──
    usb: {
      vid:            document.getElementById('usbVid').value || '0xFEED',
      pid:            document.getElementById('usbPid').value || '0x0000',
      device_version: '1.0.0',
    },

    // ── Matrix ──
    diode_direction: document.getElementById('diodeDir').value,
    matrix_pins: {
      rows:     rowPins,
      cols:     colPins,
      io_delay: parseInt(document.getElementById('cfgMatrixIoDelay').value) || 30,
    },
    debounce: parseInt(document.getElementById('cfgDebounce').value) || 5,

    // ── Tapping ──
    tapping: {
      term:                    parseInt(document.getElementById('cfgTappingTerm').value) || 200,
      permissive_hold:         isTgl('tgl-permissive-hold'),
      hold_on_other_key_press: isTgl('tgl-hold-on-other'),
      retro:                   isTgl('tgl-retro-tapping'),
    },

    // ── One Shot ──
    oneshot: {
      timeout: parseInt(document.getElementById('cfgOneshotTimeout').value) || 300,
    },

    // ── Combo ──
    combo: {
      term: parseInt(document.getElementById('cfgComboTerm').value) || 50,
    },

    // ── Leader Key ──
    leader_key: {
      timeout: parseInt(document.getElementById('cfgLeaderTimeout').value) || 300,
    },

    // ── Locking ──
    qmk: {
      locking: {
        enabled: isTgl('tgl-locking'),
        resync:  isTgl('tgl-locking-resync'),
      },
    },

    // ── Features ──
    features: {
      bootmagic:    isTgl('tgl-bootmagic'),
      mousekey:     isTgl('tgl-mousekey'),
      extrakey:     isTgl('tgl-extrakey'),
      nkro:         isTgl('tgl-nkro'),
      tap_dance:    isTgl('tgl-tapdance'),
      combo:        isTgl('tgl-combo'),
      key_override: isTgl('tgl-keyoverride'),
      oled:         isTgl('tgl-oled'),
      wpm:          isTgl('tgl-wpm'),
      autocorrect:  isTgl('tgl-autocorrect'),
      caps_word:    isTgl('tgl-capsword'),
    },
  };

  // ── Encoder ──
  const encA  = document.getElementById('encAPin').value.trim();
  const encB  = document.getElementById('encBPin').value.trim();
  const encA2 = document.getElementById('encAPin2').value.trim();
  const encB2 = document.getElementById('encBPin2').value.trim();
  if (encA && encB) {
    obj.encoder = { rotary: [] };
    obj.encoder.rotary.push({ pin_a: encA, pin_b: encB, resolution: 4 });
    if (encA2 && encB2) obj.encoder.rotary.push({ pin_a: encA2, pin_b: encB2, resolution: 4 });
    if (isTgl('tgl-encoder')) obj.features.encoder = true;
  }

  // ── RGB ── ws2812.pin per schema; rgblight.led_count + driver
  const rgbType  = document.getElementById('rgbType').value;
  const rgbCount = parseInt(document.getElementById('rgbCount').value) || 0;
  const rgbPin   = document.getElementById('rgbPin').value.trim();
  if (rgbType !== 'none' && rgbCount > 0) {
    obj.rgblight = {
      led_count: rgbCount,
      driver: rgbType === 'APA102' ? 'apa102' : 'ws2812',
    };
    if (rgbPin && rgbType !== 'APA102') obj.ws2812 = { pin: rgbPin };
    if (isTgl('tgl-rgblight'))  obj.features.rgblight   = true;
    if (isTgl('tgl-rgbmatrix')) obj.features.rgb_matrix = true;
  }

  // ── Split ──
  const serialPin    = document.getElementById('serialPin').value.trim();
  const serialDriver = document.getElementById('serialDriver').value;
  const sideDetect   = document.getElementById('sideDetect').value;
  const handPin      = document.getElementById('handPin').value.trim();
  obj.split = {
    enabled: true,
    serial: {
      driver: serialDriver || 'vendor',
      ...(serialDriver !== 'vendor' && serialPin ? { pin: serialPin } : {}),
    },
    ...(sideDetect === 'pin' && handPin ? { handedness: { pin: handPin } } : {}),
    usb_detect: { enabled: isTgl('tgl-usb-detect') },
    transport: {
      sync: {
        layer_state: isTgl('tgl-layer-sync'),
        modifiers:   isTgl('tgl-mods-sync'),
        indicators:  isTgl('tgl-led-sync'),
      },
      watchdog: isTgl('tgl-watchdog'),
    },
  };

  // Merge: start from preserved raw JSON, overlay our edited keys
  const merged = Object.assign({}, _rawInfoJson, obj);

  // Deep-merge nested objects
  for (const key of ['usb', 'features', 'split', 'tapping', 'oneshot', 'combo', 'leader_key', 'qmk']) {
    if (_rawInfoJson[key] && obj[key]) {
      merged[key] = Object.assign({}, _rawInfoJson[key], obj[key]);
    }
  }

  // Encoder and rgblight: only overwrite if we have values
  if (!obj.encoder && _rawInfoJson.encoder)  merged.encoder  = _rawInfoJson.encoder;
  if (!obj.rgblight && _rawInfoJson.rgblight) merged.rgblight = _rawInfoJson.rgblight;

  // Serialize layouts section separately in compact row format
  const layoutName = document.getElementById('layoutName')?.value || 'LAYOUT';
  const layoutArr = (typeof layoutKeys !== 'undefined' && layoutKeys.length > 0)
    ? buildLayoutObject()
    : (merged.layouts?.[layoutName]?.layout || []);

  const mergedNoLayouts = Object.assign({}, merged);
  delete mergedNoLayouts.layouts;

  let base = JSON.stringify(mergedNoLayouts, (k, v) => v === undefined ? undefined : v, 4);

  if (layoutArr.length > 0) {
    const compactLayout = layoutJsonToString(layoutArr, '            ', '            ');
    const layoutsSection = [
      '    "layouts": {',
      `        "${layoutName}": {`,
      `            "layout": ${compactLayout}`,
      '        }',
      '    }',
    ].join('\n');
    base = base.slice(0, -1) + ',\n' + layoutsSection + '\n}';
  }

  return base;
}

function genKeymapC() {
  const rows = parseInt(document.getElementById('kbRows').value) || 4;
  const cols = parseInt(document.getElementById('kbCols').value) || 6;
  const layoutMacro = (document.getElementById('layoutName')?.value || 'LAYOUT').trim() || 'LAYOUT';

  // Number of keys per layer must match the LAYOUT macro exactly.
  // Source of truth: layoutKeys array (from Layout Editor / info.json).
  // If layout is defined, use its key count. Otherwise fall back to rows*cols*2.
  const layoutKeyCount = (typeof layoutKeys !== 'undefined' && layoutKeys.length > 0)
    ? layoutKeys.length
    : rows * cols * 2;

  // Build a matrix-position → keycode lookup from layoutKeys so we can
  // output keys in the exact order the LAYOUT macro expects.
  // layoutKeys[i].matrix = [row, col] maps to keymapData[layer][row][col].
  // Map a layoutKey's matrix coord back to the visual grid slot
  // Visual grid: left half matRow<rows -> vRow=matRow, vCol=matCol
  //              right half matRow>=rows -> vRow=matRow-rows, vCol=matCol+cols
  const matrixToKeycode = (layer, layoutEntry) => {
    const [matRow, matCol] = layoutEntry.matrix;
    let vRow, vCol;
    if (matRow < rows) {
      vRow = matRow; vCol = matCol;
    } else {
      vRow = matRow - rows; vCol = matCol + cols;
    }
    return (keymapData[layer]?.[vRow]?.[vCol]) || 'KC_TRNS';
  };

  let out = `// keymap.c — generated by QMK Visual Editor
#include QMK_KEYBOARD_H

enum layers { `;
  out += LAYER_NAMES.join(', ');
  out += ` };\n\nconst uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n\n`;

  for (let l = 0; l < keymapData.length; l++) {
    out += `    [${LAYER_NAMES[l] || 'LAYER_' + l}] = ${layoutMacro}(\n`;

    if (typeof layoutKeys !== 'undefined' && layoutKeys.length > 0) {
      // Use layout order — keys in the exact sequence the macro expects
      const keycodes = layoutKeys.map(lk => matrixToKeycode(l, lk));
      // Output ~8 per line for readability
      const lineSize = cols * 2 || 8;
      for (let i = 0; i < keycodes.length; i += lineSize) {
        const slice = keycodes.slice(i, i + lineSize);
        const isLast = i + lineSize >= keycodes.length;
        out += `        ${slice.join(', ')}${isLast ? '' : ','}\n`;
      }
    } else {
      // Fallback: flat grid order
      const allKeys = [];
      for (let r = 0; r < rows; r++) {
        const rowKeys = keymapData[l]?.[r] || [];
        for (let c = 0; c < cols * 2; c++) allKeys.push(rowKeys[c] || 'KC_TRNS');
      }
      for (let r = 0; r < rows; r++) {
        const slice = allKeys.slice(r * cols * 2, (r + 1) * cols * 2);
        const isLast = r === rows - 1;
        out += `        ${slice.join(', ')}${isLast ? '' : ','}\n`;
      }
    }

    out += `    )`;
    if (l < keymapData.length - 1) out += ',';
    out += '\n\n';
  }
  out += `};\n`;
  return out;
}
